import type { YakuDefinition, YakuId } from './types.ts'

export const YAKU_TABLE: Record<YakuId, YakuDefinition> = {
  riichi: {
    id: 'riichi',
    nameJp: '立直',
    nameEn: 'Riichi',
    han: { closed: 1 },
    description: '門前でテンパイを宣言する。',
  },
  doubleRiichi: {
    id: 'doubleRiichi',
    nameJp: 'ダブル立直',
    nameEn: 'Double Riichi',
    han: { closed: 2 },
    description: '第一巡目にリーチを宣言する。',
  },
  ippatsu: {
    id: 'ippatsu',
    nameJp: '一発',
    nameEn: 'Ippatsu',
    han: { closed: 1 },
    description: 'リーチ後、他家の副露を挟まず1巡以内に和了する。',
  },
  menzenTsumo: {
    id: 'menzenTsumo',
    nameJp: '門前清自摸和',
    nameEn: 'Menzen Tsumo',
    han: { closed: 1 },
    description: '門前でツモ和了する。',
  },
  pinfu: {
    id: 'pinfu',
    nameJp: '平和',
    nameEn: 'Pinfu',
    han: { closed: 1 },
    description: '四面子すべて順子、雀頭は役牌以外、両面待ちで和了する。',
  },
  tanyao: {
    id: 'tanyao',
    nameJp: '断幺九',
    nameEn: 'Tanyao',
    han: { closed: 1, open: 1 },
    description: '2〜8の数牌のみで手牌を構成する。',
  },
  yakuhaiHaku: {
    id: 'yakuhaiHaku',
    nameJp: '役牌(白)',
    nameEn: 'Yakuhai (Haku)',
    han: { closed: 1, open: 1 },
    description: '白の刻子・槓子を含む。',
  },
  yakuhaiHatsu: {
    id: 'yakuhaiHatsu',
    nameJp: '役牌(發)',
    nameEn: 'Yakuhai (Hatsu)',
    han: { closed: 1, open: 1 },
    description: '發の刻子・槓子を含む。',
  },
  yakuhaiChun: {
    id: 'yakuhaiChun',
    nameJp: '役牌(中)',
    nameEn: 'Yakuhai (Chun)',
    han: { closed: 1, open: 1 },
    description: '中の刻子・槓子を含む。',
  },
  yakuhaiSeatWind: {
    id: 'yakuhaiSeatWind',
    nameJp: '役牌(自風)',
    nameEn: 'Yakuhai (Seat Wind)',
    han: { closed: 1, open: 1 },
    description: '自風牌の刻子・槓子を含む。',
  },
  yakuhaiRoundWind: {
    id: 'yakuhaiRoundWind',
    nameJp: '役牌(場風)',
    nameEn: 'Yakuhai (Round Wind)',
    han: { closed: 1, open: 1 },
    description: '場風牌の刻子・槓子を含む。',
  },
  iipeikou: {
    id: 'iipeikou',
    nameJp: '一盃口',
    nameEn: 'Iipeikou',
    han: { closed: 1 },
    description: '同一の順子が2組ある（門前限定）。',
  },
  toitoi: {
    id: 'toitoi',
    nameJp: '対々和',
    nameEn: 'Toitoi',
    han: { closed: 2, open: 2 },
    description: '四面子すべて刻子・槓子で構成する。',
  },
  sanankou: {
    id: 'sanankou',
    nameJp: '三暗刻',
    nameEn: 'Sanankou',
    han: { closed: 2, open: 2 },
    description: '暗刻（暗槓を含む）を3組以上持つ。',
  },
  chanta: {
    id: 'chanta',
    nameJp: '混全帯幺九',
    nameEn: 'Chanta',
    han: { closed: 2, open: 1 },
    description: 'すべての面子・雀頭に么九牌を含む。',
  },
  honitsu: {
    id: 'honitsu',
    nameJp: '混一色',
    nameEn: 'Honitsu',
    han: { closed: 3, open: 2 },
    description: '一種類の数牌と字牌のみで構成する。',
  },
  chinitsu: {
    id: 'chinitsu',
    nameJp: '清一色',
    nameEn: 'Chinitsu',
    han: { closed: 6, open: 5 },
    description: '一種類の数牌のみで構成する。',
  },
  chiitoitsu: {
    id: 'chiitoitsu',
    nameJp: '七対子',
    nameEn: 'Chiitoitsu',
    han: { closed: 2 },
    description: '7組の対子で構成する（門前限定、符は25固定）。',
  },
  haitei: {
    id: 'haitei',
    nameJp: '海底摸月',
    nameEn: 'Haitei',
    han: { closed: 1, open: 1 },
    description: '最後の牌でツモ和了する。',
  },
  houtei: {
    id: 'houtei',
    nameJp: '河底撈魚',
    nameEn: 'Houtei',
    han: { closed: 1, open: 1 },
    description: '最後の捨て牌でロン和了する。',
  },
  rinshan: {
    id: 'rinshan',
    nameJp: '嶺上開花',
    nameEn: 'Rinshan Kaihou',
    han: { closed: 1, open: 1 },
    description: '槓の嶺上牌でツモ和了する。',
  },
  chankan: {
    id: 'chankan',
    nameJp: '槍槓',
    nameEn: 'Chankan',
    han: { closed: 1, open: 1 },
    description: '他家の加槓をロンする。',
  },
}
